# Generated by Django 6.0.5 on 2026-05-20 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanAplikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wajib_bukti_foto', models.BooleanField(default=True, help_text='Jika aktif, pengguna harus melampirkan foto saat melapor pelanggaran.', verbose_name='Wajib upload foto bukti')),
                ('izinkan_custom_guru', models.BooleanField(default=True, help_text='Jika aktif, Guru bisa memilih "Lainnya" dan mendeskripsikan pelanggaran sendiri.', verbose_name='Guru boleh input jenis pelanggaran baru')),
                ('izinkan_custom_osis', models.BooleanField(default=False, help_text='Jika aktif, OSIS bisa menuliskan deskripsi untuk pelanggaran yang belum tercantum.', verbose_name='OSIS boleh mendeskripsikan pelanggaran yang belum ada')),
                ('reset_poin_aktif', models.BooleanField(default=True, help_text='Jika aktif, total poin siswa direset setiap awal bulan via APScheduler.', verbose_name='Reset poin bulanan aktif')),
                ('tanggal_reset', models.PositiveSmallIntegerField(default=1, help_text='Tanggal dalam bulan saat reset dijalankan (1–28).', verbose_name='Tanggal reset (hari ke-)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diubah_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Terakhir diubah oleh')),
            ],
            options={
                'verbose_name': 'Pengaturan Aplikasi',
                'verbose_name_plural': 'Pengaturan Aplikasi',
            },
        ),
    ]
