# Generated by Django 6.0.5 on 2026-05-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_bk_teacher',
            field=models.BooleanField(default=False, help_text='Guru yang juga bertugas konseling (dual role Guru+BK).'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_homeroom_teacher',
            field=models.BooleanField(default=False, help_text='Guru yang menjadi wali kelas. Digunakan untuk menampilkan menu khusus wali kelas.'),
        ),
    ]
