# Generated by Django 6.0.5 on 2026-05-20 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=50)),
                ('tingkat', models.CharField(choices=[('10', 'Kelas 10'), ('11', 'Kelas 11'), ('12', 'Kelas 12')], max_length=2)),
                ('tahun_ajaran', models.CharField(help_text='Format: 2024/2025', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kelas_dibuat', to=settings.AUTH_USER_MODEL)),
                ('wali_kelas', models.ForeignKey(blank=True, limit_choices_to={'role': 'guru'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kelas_diampu', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kelas',
                'verbose_name_plural': 'Kelas',
                'ordering': ['tingkat', 'nama_kelas'],
                'unique_together': {('nama_kelas', 'tahun_ajaran')},
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='siswa/')),
                ('total_poin', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ditambah_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siswa_ditambahkan', to=settings.AUTH_USER_MODEL)),
                ('kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siswa', to='academics.kelas')),
            ],
            options={
                'verbose_name': 'Siswa',
                'verbose_name_plural': 'Siswa',
                'ordering': ['nama'],
            },
        ),
    ]
