# Generated by Django 6.0.5 on 2026-05-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='tingkat',
            field=models.CharField(choices=[('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], max_length=3),
        ),
    ]
