# Generated by Django 6.0.5 on 2026-05-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_copy_wali_kelas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelas',
            name='dibuat_oleh',
        ),
        migrations.AlterField(
            model_name='kelas',
            name='wali_kelas',
            field=models.CharField(blank=True, help_text='Nama wali kelas (ditulis manual)', max_length=150, null=True),
        ),
    ]
