# Generated by Django 6.0.5 on 2026-05-20 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_remove_kelas_dibuat_oleh_alter_kelas_wali_kelas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kelas',
            old_name='tahun_ajaran',
            new_name='angkatan',
        ),
        migrations.AlterUniqueTogether(
            name='kelas',
            unique_together={('nama_kelas', 'angkatan')},
        ),
    ]
