# Generated by Django 6.0.5 on 2026-05-20 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_rename_tahun_ajaran_kelas_angkatan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswa',
            name='ditambah_oleh',
        ),
    ]
