# Generated by Django 6.0.5 on 2026-05-21 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_remove_siswa_ditambah_oleh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='kelas',
            old_name='angkatan',
            new_name='tahun_ajaran',
        ),
        migrations.AlterUniqueTogether(
            name='kelas',
            unique_together={('nama_kelas', 'tahun_ajaran')},
        ),
        migrations.AddField(
            model_name='kelas',
            name='dibuat_oleh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kelas_dibuat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='siswa',
            name='ditambah_oleh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siswa_ditambahkan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='siswa',
            name='is_wajib_bk',
            field=models.BooleanField(default=False, help_text='True jika total_poin >= 75. Di-set otomatis.'),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='tingkat',
            field=models.CharField(choices=[('10', 'Kelas 10'), ('11', 'Kelas 11'), ('12', 'Kelas 12')], max_length=2),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='wali_kelas',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'guru'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kelas_diampu', to=settings.AUTH_USER_MODEL),
        ),
    ]
