# Generated by Django 6.0.5 on 2026-06-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_rename_angkatan_kelas_tahun_ajaran_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='is_osis',
            field=models.BooleanField(default=False, help_text='True jika siswa ini anggota OSIS.'),
        ),
    ]
