# Generated by Django 6.0.5 on 2026-05-20 02:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisPelanggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('kategori', models.CharField(choices=[('ringan', 'Ringan'), ('sedang', 'Sedang'), ('berat', 'Berat')], default='ringan', max_length=10)),
                ('deskripsi', models.TextField(blank=True)),
                ('poin_default', models.PositiveIntegerField(default=0, help_text='0 jika custom — BK yang menetapkan poin setelah review.')),
                ('perlu_persetujuan_bk', models.BooleanField(default=False, help_text='True secara otomatis untuk semua laporan OSIS dan jenis custom.')),
                ('is_custom', models.BooleanField(default=False, help_text='True jika dibuat on-the-fly saat input pelanggaran.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jenis_pelanggaran_dibuat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jenis Pelanggaran',
                'verbose_name_plural': 'Jenis Pelanggaran',
                'ordering': ['kategori', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='Pelanggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi_tambahan', models.TextField(blank=True, help_text='Keterangan tambahan atau isi deskripsi jika jenis custom.')),
                ('poin_ditetapkan', models.PositiveIntegerField(default=0, help_text='Disalin dari poin_default saat input; bisa diubah BK saat ACC.')),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu Persetujuan'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('langsung', 'Langsung Berlaku')], default='menunggu', max_length=10)),
                ('tanggal_kejadian', models.DateField(default=django.utils.timezone.now)),
                ('bukti_foto', models.ImageField(blank=True, null=True, upload_to='bukti_pelanggaran/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dilaporkan_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pelanggaran_dilaporkan', to=settings.AUTH_USER_MODEL)),
                ('jenis_pelanggaran', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pelanggaran', to='violations.jenispelanggaran')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pelanggaran', to='academics.siswa')),
            ],
            options={
                'verbose_name': 'Pelanggaran',
                'verbose_name_plural': 'Pelanggaran',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersetujuanBK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keputusan', models.CharField(choices=[('setuju', 'Setuju'), ('tolak', 'Tolak')], max_length=6)),
                ('catatan', models.TextField(blank=True)),
                ('poin_final', models.PositiveIntegerField(default=0, help_text='BK bisa mengubah dari poin_default jenis.')),
                ('diproses_at', models.DateTimeField(auto_now_add=True)),
                ('bk', models.ForeignKey(limit_choices_to={'role': 'bk'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persetujuan_bk', to=settings.AUTH_USER_MODEL)),
                ('pelanggaran', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persetujuan', to='violations.pelanggaran')),
            ],
            options={
                'verbose_name': 'Persetujuan BK',
                'verbose_name_plural': 'Persetujuan BK',
            },
        ),
        migrations.CreateModel(
            name='HistoryPoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.PositiveSmallIntegerField(help_text='1–12')),
                ('tahun', models.PositiveSmallIntegerField()),
                ('total_poin', models.PositiveIntegerField(help_text='Poin yang terakumulasi selama bulan berjalan sebelum direset.')),
                ('jumlah_kasus', models.PositiveIntegerField(default=0, help_text='Jumlah pelanggaran yang tercatat di bulan ini.')),
                ('direset_pada', models.DateTimeField(auto_now_add=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_poin', to='academics.siswa')),
            ],
            options={
                'verbose_name': 'History Poin',
                'verbose_name_plural': 'History Poin',
                'ordering': ['-tahun', '-bulan', 'siswa__nama'],
                'unique_together': {('siswa', 'bulan', 'tahun')},
            },
        ),
    ]
