# Generated by Django 6.0.5 on 2026-05-20 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('violations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('laporan_baru', 'Laporan Baru'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('poin_ditetapkan', 'Poin Ditetapkan')], default='laporan_baru', max_length=20)),
                ('pesan', models.TextField()),
                ('sudah_dibaca', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pelanggaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to='violations.pelanggaran')),
                ('penerima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notifikasi',
                'verbose_name_plural': 'Notifikasi',
                'ordering': ['-created_at'],
            },
        ),
    ]
