# Generated by Django 6.0.5 on 2026-05-21 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_rename_angkatan_kelas_tahun_ajaran_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifikasi',
            name='siswa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to='academics.siswa'),
        ),
        migrations.AlterField(
            model_name='notifikasi',
            name='tipe',
            field=models.CharField(choices=[('laporan_baru', 'Laporan Baru'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('poin_ditetapkan', 'Poin Ditetapkan'), ('wajib_bk', 'Wajib BK')], default='laporan_baru', max_length=20),
        ),
    ]
